[package]
name = "mysql-test"
version = "0.1.0"
authors = ["Peter Farr <peter@prismaphonic.com>"]
edition = "2021"

[dependencies]
mysql_async = "0.29"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
